/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAuthRouteRouteImport } from './routes/dashboard/auth/route'
import { Route as DashboardAuthUsersRouteRouteImport } from './routes/dashboard/auth/users/route'
import { Route as DashboardAuthUsersIndexRouteImport } from './routes/dashboard/auth/users/index'
import { Route as DashboardAuthUsersUseridRouteImport } from './routes/dashboard/auth/users/$userid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuthRouteRoute = DashboardAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuthUsersRouteRoute = DashboardAuthUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthUsersIndexRoute = DashboardAuthUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAuthUsersRouteRoute,
} as any)
const DashboardAuthUsersUseridRoute =
  DashboardAuthUsersUseridRouteImport.update({
    id: '/$userid',
    path: '/$userid',
    getParentRoute: () => DashboardAuthUsersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auth/users': typeof DashboardAuthUsersRouteRouteWithChildren
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users/': typeof DashboardAuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users': typeof DashboardAuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auth/users': typeof DashboardAuthUsersRouteRouteWithChildren
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users/': typeof DashboardAuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard/'
    | '/dashboard/auth/users'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard/'
    | '/dashboard/auth/users'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auth': {
      id: '/dashboard/auth'
      path: '/auth'
      fullPath: '/dashboard/auth'
      preLoaderRoute: typeof DashboardAuthRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auth/users': {
      id: '/dashboard/auth/users'
      path: '/users'
      fullPath: '/dashboard/auth/users'
      preLoaderRoute: typeof DashboardAuthUsersRouteRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/auth/users/': {
      id: '/dashboard/auth/users/'
      path: '/'
      fullPath: '/dashboard/auth/users/'
      preLoaderRoute: typeof DashboardAuthUsersIndexRouteImport
      parentRoute: typeof DashboardAuthUsersRouteRoute
    }
    '/dashboard/auth/users/$userid': {
      id: '/dashboard/auth/users/$userid'
      path: '/$userid'
      fullPath: '/dashboard/auth/users/$userid'
      preLoaderRoute: typeof DashboardAuthUsersUseridRouteImport
      parentRoute: typeof DashboardAuthUsersRouteRoute
    }
  }
}

interface DashboardAuthUsersRouteRouteChildren {
  DashboardAuthUsersUseridRoute: typeof DashboardAuthUsersUseridRoute
  DashboardAuthUsersIndexRoute: typeof DashboardAuthUsersIndexRoute
}

const DashboardAuthUsersRouteRouteChildren: DashboardAuthUsersRouteRouteChildren =
  {
    DashboardAuthUsersUseridRoute: DashboardAuthUsersUseridRoute,
    DashboardAuthUsersIndexRoute: DashboardAuthUsersIndexRoute,
  }

const DashboardAuthUsersRouteRouteWithChildren =
  DashboardAuthUsersRouteRoute._addFileChildren(
    DashboardAuthUsersRouteRouteChildren,
  )

interface DashboardAuthRouteRouteChildren {
  DashboardAuthUsersRouteRoute: typeof DashboardAuthUsersRouteRouteWithChildren
}

const DashboardAuthRouteRouteChildren: DashboardAuthRouteRouteChildren = {
  DashboardAuthUsersRouteRoute: DashboardAuthUsersRouteRouteWithChildren,
}

const DashboardAuthRouteRouteWithChildren =
  DashboardAuthRouteRoute._addFileChildren(DashboardAuthRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAuthRouteRoute: typeof DashboardAuthRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAuthRouteRoute: DashboardAuthRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
