/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAuthRouteRouteImport } from './routes/dashboard/auth/route'
import { Route as DashboardAuthUsersRouteRouteImport } from './routes/dashboard/auth/users/route'
import { Route as DashboardAuthPermissionsRouteRouteImport } from './routes/dashboard/auth/permissions/route'
import { Route as DashboardAuthGroupsRouteRouteImport } from './routes/dashboard/auth/groups/route'
import { Route as DashboardAuthUsersIndexRouteImport } from './routes/dashboard/auth/users/index'
import { Route as DashboardAuthPermissionsIndexRouteImport } from './routes/dashboard/auth/permissions/index'
import { Route as DashboardAuthGroupsIndexRouteImport } from './routes/dashboard/auth/groups/index'
import { Route as DashboardAuthUsersCreateRouteImport } from './routes/dashboard/auth/users/create'
import { Route as DashboardAuthUsersUseridRouteImport } from './routes/dashboard/auth/users/$userid'
import { Route as DashboardAuthPermissionsPermidRouteImport } from './routes/dashboard/auth/permissions/$permid'
import { Route as DashboardAuthGroupsCreateRouteImport } from './routes/dashboard/auth/groups/create'
import { Route as DashboardAuthGroupsGroupidRouteImport } from './routes/dashboard/auth/groups/$groupid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuthRouteRoute = DashboardAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuthUsersRouteRoute = DashboardAuthUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthPermissionsRouteRoute =
  DashboardAuthPermissionsRouteRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => DashboardAuthRouteRoute,
  } as any)
const DashboardAuthGroupsRouteRoute =
  DashboardAuthGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => DashboardAuthRouteRoute,
  } as any)
const DashboardAuthUsersIndexRoute = DashboardAuthUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAuthUsersRouteRoute,
} as any)
const DashboardAuthPermissionsIndexRoute =
  DashboardAuthPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthPermissionsRouteRoute,
  } as any)
const DashboardAuthGroupsIndexRoute =
  DashboardAuthGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthGroupsRouteRoute,
  } as any)
const DashboardAuthUsersCreateRoute =
  DashboardAuthUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardAuthUsersRouteRoute,
  } as any)
const DashboardAuthUsersUseridRoute =
  DashboardAuthUsersUseridRouteImport.update({
    id: '/$userid',
    path: '/$userid',
    getParentRoute: () => DashboardAuthUsersRouteRoute,
  } as any)
const DashboardAuthPermissionsPermidRoute =
  DashboardAuthPermissionsPermidRouteImport.update({
    id: '/$permid',
    path: '/$permid',
    getParentRoute: () => DashboardAuthPermissionsRouteRoute,
  } as any)
const DashboardAuthGroupsCreateRoute =
  DashboardAuthGroupsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardAuthGroupsRouteRoute,
  } as any)
const DashboardAuthGroupsGroupidRoute =
  DashboardAuthGroupsGroupidRouteImport.update({
    id: '/$groupid',
    path: '/$groupid',
    getParentRoute: () => DashboardAuthGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auth/groups': typeof DashboardAuthGroupsRouteRouteWithChildren
  '/dashboard/auth/permissions': typeof DashboardAuthPermissionsRouteRouteWithChildren
  '/dashboard/auth/users': typeof DashboardAuthUsersRouteRouteWithChildren
  '/dashboard/auth/groups/$groupid': typeof DashboardAuthGroupsGroupidRoute
  '/dashboard/auth/groups/create': typeof DashboardAuthGroupsCreateRoute
  '/dashboard/auth/permissions/$permid': typeof DashboardAuthPermissionsPermidRoute
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users/create': typeof DashboardAuthUsersCreateRoute
  '/dashboard/auth/groups/': typeof DashboardAuthGroupsIndexRoute
  '/dashboard/auth/permissions/': typeof DashboardAuthPermissionsIndexRoute
  '/dashboard/auth/users/': typeof DashboardAuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/auth/groups/$groupid': typeof DashboardAuthGroupsGroupidRoute
  '/dashboard/auth/groups/create': typeof DashboardAuthGroupsCreateRoute
  '/dashboard/auth/permissions/$permid': typeof DashboardAuthPermissionsPermidRoute
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users/create': typeof DashboardAuthUsersCreateRoute
  '/dashboard/auth/groups': typeof DashboardAuthGroupsIndexRoute
  '/dashboard/auth/permissions': typeof DashboardAuthPermissionsIndexRoute
  '/dashboard/auth/users': typeof DashboardAuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auth/groups': typeof DashboardAuthGroupsRouteRouteWithChildren
  '/dashboard/auth/permissions': typeof DashboardAuthPermissionsRouteRouteWithChildren
  '/dashboard/auth/users': typeof DashboardAuthUsersRouteRouteWithChildren
  '/dashboard/auth/groups/$groupid': typeof DashboardAuthGroupsGroupidRoute
  '/dashboard/auth/groups/create': typeof DashboardAuthGroupsCreateRoute
  '/dashboard/auth/permissions/$permid': typeof DashboardAuthPermissionsPermidRoute
  '/dashboard/auth/users/$userid': typeof DashboardAuthUsersUseridRoute
  '/dashboard/auth/users/create': typeof DashboardAuthUsersCreateRoute
  '/dashboard/auth/groups/': typeof DashboardAuthGroupsIndexRoute
  '/dashboard/auth/permissions/': typeof DashboardAuthPermissionsIndexRoute
  '/dashboard/auth/users/': typeof DashboardAuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard/'
    | '/dashboard/auth/groups'
    | '/dashboard/auth/permissions'
    | '/dashboard/auth/users'
    | '/dashboard/auth/groups/$groupid'
    | '/dashboard/auth/groups/create'
    | '/dashboard/auth/permissions/$permid'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users/create'
    | '/dashboard/auth/groups/'
    | '/dashboard/auth/permissions/'
    | '/dashboard/auth/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard'
    | '/dashboard/auth/groups/$groupid'
    | '/dashboard/auth/groups/create'
    | '/dashboard/auth/permissions/$permid'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users/create'
    | '/dashboard/auth/groups'
    | '/dashboard/auth/permissions'
    | '/dashboard/auth/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/auth'
    | '/dashboard/'
    | '/dashboard/auth/groups'
    | '/dashboard/auth/permissions'
    | '/dashboard/auth/users'
    | '/dashboard/auth/groups/$groupid'
    | '/dashboard/auth/groups/create'
    | '/dashboard/auth/permissions/$permid'
    | '/dashboard/auth/users/$userid'
    | '/dashboard/auth/users/create'
    | '/dashboard/auth/groups/'
    | '/dashboard/auth/permissions/'
    | '/dashboard/auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auth': {
      id: '/dashboard/auth'
      path: '/auth'
      fullPath: '/dashboard/auth'
      preLoaderRoute: typeof DashboardAuthRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auth/users': {
      id: '/dashboard/auth/users'
      path: '/users'
      fullPath: '/dashboard/auth/users'
      preLoaderRoute: typeof DashboardAuthUsersRouteRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/auth/permissions': {
      id: '/dashboard/auth/permissions'
      path: '/permissions'
      fullPath: '/dashboard/auth/permissions'
      preLoaderRoute: typeof DashboardAuthPermissionsRouteRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/auth/groups': {
      id: '/dashboard/auth/groups'
      path: '/groups'
      fullPath: '/dashboard/auth/groups'
      preLoaderRoute: typeof DashboardAuthGroupsRouteRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/auth/users/': {
      id: '/dashboard/auth/users/'
      path: '/'
      fullPath: '/dashboard/auth/users/'
      preLoaderRoute: typeof DashboardAuthUsersIndexRouteImport
      parentRoute: typeof DashboardAuthUsersRouteRoute
    }
    '/dashboard/auth/permissions/': {
      id: '/dashboard/auth/permissions/'
      path: '/'
      fullPath: '/dashboard/auth/permissions/'
      preLoaderRoute: typeof DashboardAuthPermissionsIndexRouteImport
      parentRoute: typeof DashboardAuthPermissionsRouteRoute
    }
    '/dashboard/auth/groups/': {
      id: '/dashboard/auth/groups/'
      path: '/'
      fullPath: '/dashboard/auth/groups/'
      preLoaderRoute: typeof DashboardAuthGroupsIndexRouteImport
      parentRoute: typeof DashboardAuthGroupsRouteRoute
    }
    '/dashboard/auth/users/create': {
      id: '/dashboard/auth/users/create'
      path: '/create'
      fullPath: '/dashboard/auth/users/create'
      preLoaderRoute: typeof DashboardAuthUsersCreateRouteImport
      parentRoute: typeof DashboardAuthUsersRouteRoute
    }
    '/dashboard/auth/users/$userid': {
      id: '/dashboard/auth/users/$userid'
      path: '/$userid'
      fullPath: '/dashboard/auth/users/$userid'
      preLoaderRoute: typeof DashboardAuthUsersUseridRouteImport
      parentRoute: typeof DashboardAuthUsersRouteRoute
    }
    '/dashboard/auth/permissions/$permid': {
      id: '/dashboard/auth/permissions/$permid'
      path: '/$permid'
      fullPath: '/dashboard/auth/permissions/$permid'
      preLoaderRoute: typeof DashboardAuthPermissionsPermidRouteImport
      parentRoute: typeof DashboardAuthPermissionsRouteRoute
    }
    '/dashboard/auth/groups/create': {
      id: '/dashboard/auth/groups/create'
      path: '/create'
      fullPath: '/dashboard/auth/groups/create'
      preLoaderRoute: typeof DashboardAuthGroupsCreateRouteImport
      parentRoute: typeof DashboardAuthGroupsRouteRoute
    }
    '/dashboard/auth/groups/$groupid': {
      id: '/dashboard/auth/groups/$groupid'
      path: '/$groupid'
      fullPath: '/dashboard/auth/groups/$groupid'
      preLoaderRoute: typeof DashboardAuthGroupsGroupidRouteImport
      parentRoute: typeof DashboardAuthGroupsRouteRoute
    }
  }
}

interface DashboardAuthGroupsRouteRouteChildren {
  DashboardAuthGroupsGroupidRoute: typeof DashboardAuthGroupsGroupidRoute
  DashboardAuthGroupsCreateRoute: typeof DashboardAuthGroupsCreateRoute
  DashboardAuthGroupsIndexRoute: typeof DashboardAuthGroupsIndexRoute
}

const DashboardAuthGroupsRouteRouteChildren: DashboardAuthGroupsRouteRouteChildren =
  {
    DashboardAuthGroupsGroupidRoute: DashboardAuthGroupsGroupidRoute,
    DashboardAuthGroupsCreateRoute: DashboardAuthGroupsCreateRoute,
    DashboardAuthGroupsIndexRoute: DashboardAuthGroupsIndexRoute,
  }

const DashboardAuthGroupsRouteRouteWithChildren =
  DashboardAuthGroupsRouteRoute._addFileChildren(
    DashboardAuthGroupsRouteRouteChildren,
  )

interface DashboardAuthPermissionsRouteRouteChildren {
  DashboardAuthPermissionsPermidRoute: typeof DashboardAuthPermissionsPermidRoute
  DashboardAuthPermissionsIndexRoute: typeof DashboardAuthPermissionsIndexRoute
}

const DashboardAuthPermissionsRouteRouteChildren: DashboardAuthPermissionsRouteRouteChildren =
  {
    DashboardAuthPermissionsPermidRoute: DashboardAuthPermissionsPermidRoute,
    DashboardAuthPermissionsIndexRoute: DashboardAuthPermissionsIndexRoute,
  }

const DashboardAuthPermissionsRouteRouteWithChildren =
  DashboardAuthPermissionsRouteRoute._addFileChildren(
    DashboardAuthPermissionsRouteRouteChildren,
  )

interface DashboardAuthUsersRouteRouteChildren {
  DashboardAuthUsersUseridRoute: typeof DashboardAuthUsersUseridRoute
  DashboardAuthUsersCreateRoute: typeof DashboardAuthUsersCreateRoute
  DashboardAuthUsersIndexRoute: typeof DashboardAuthUsersIndexRoute
}

const DashboardAuthUsersRouteRouteChildren: DashboardAuthUsersRouteRouteChildren =
  {
    DashboardAuthUsersUseridRoute: DashboardAuthUsersUseridRoute,
    DashboardAuthUsersCreateRoute: DashboardAuthUsersCreateRoute,
    DashboardAuthUsersIndexRoute: DashboardAuthUsersIndexRoute,
  }

const DashboardAuthUsersRouteRouteWithChildren =
  DashboardAuthUsersRouteRoute._addFileChildren(
    DashboardAuthUsersRouteRouteChildren,
  )

interface DashboardAuthRouteRouteChildren {
  DashboardAuthGroupsRouteRoute: typeof DashboardAuthGroupsRouteRouteWithChildren
  DashboardAuthPermissionsRouteRoute: typeof DashboardAuthPermissionsRouteRouteWithChildren
  DashboardAuthUsersRouteRoute: typeof DashboardAuthUsersRouteRouteWithChildren
}

const DashboardAuthRouteRouteChildren: DashboardAuthRouteRouteChildren = {
  DashboardAuthGroupsRouteRoute: DashboardAuthGroupsRouteRouteWithChildren,
  DashboardAuthPermissionsRouteRoute:
    DashboardAuthPermissionsRouteRouteWithChildren,
  DashboardAuthUsersRouteRoute: DashboardAuthUsersRouteRouteWithChildren,
}

const DashboardAuthRouteRouteWithChildren =
  DashboardAuthRouteRoute._addFileChildren(DashboardAuthRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAuthRouteRoute: typeof DashboardAuthRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAuthRouteRoute: DashboardAuthRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
